### PR TITLE
Breakfast edits

### LINKED ISSUE #8: Breakfast Recipe
## 💬 Discussion topic

What do people typically like to eat for breakfast?

## ❗ Potential issues

Do people typically like a smaller breakfast or start with a big meal?
Do people like sweet breakfast or savory.

## 👥 People to consult

@anna586 @peterkossar @lmjchen @Gityashi 

## 📃 Details

Let's agree on what people would like to eat for breakfast.

### LINKED ISSUE #9: Breakfast Beverage?
## 💬 Discussion topic

What do people like to drink for Breakfast?

## ❗ Potential issues

Do we have people who require coffee?
If people require coffee -> what kind? Espresso? Latte? Drip coffee?
Do we have coffee haters?
Are some people lactose intolerant and want milk alternatives?

## 👥 People to consult

@anna586 @peterkossar @lmjchen @Gityashi @mcroeller1 

## 📃 Details

Please let me know what your preferences are for breakfast beverages

### PR DESCRIPTION
**Pull request by Gityashi**
## 🎯 Objective

Fill out the breakfast recipe.

## 🛠️ Changes made

Updates to equipment list:
1.) Added spatula for flapjack flippin.  2.) Added bowls and spoons for toppings bar. 3.) Fixed typo: "griffle" -> "griddle"

Added Nutella as a topping suggestion.

## 👥 Who needs to review this Pull Request? 

@anna586 @peterkossar @lmjchen @mcroeller1 
Can someone please approve & merge this commit?

_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Comment by mcroeller1** [comment]
@anna586 @lmjchen can you please approve this pull request?

**Review by mcroeller1 — APPROVED** [review]
Ship it!

**Review by lmjchen — APPROVED** [review]
Nice work!

**Comment by anna586** [comment]
Great! Ship

**Pull request merged**
